# Generated by Django 3.1.7 on 2021-03-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webapp',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
